/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/App/Footer.vue')['default']
    AppNavbar: typeof import('./src/components/App/Navbar.vue')['default']
    BaseLink: typeof import('./src/components/Base/Link.vue')['default']
    BaseNavLink: typeof import('./src/components/Base/NavLink.vue')['default']
    DarkToggler: typeof import('./src/components/DarkToggler.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImgSwiper: typeof import('./src/components/ImgSwiper.vue')['default']
    Layout: typeof import('./src/components/Layout/Index.vue')['default']
    Perspective: typeof import('./src/components/Perspective.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
